--<ScriptOptions statementTerminator=";"/>

ALTER TABLE CLINIC.NRS DROP CONSTRAINT FK_NRS_PID;

ALTER TABLE CLINIC.DIAGANOSED_WITH DROP CONSTRAINT FK_DIAGANOSED_WITH_DGNSS_ID;

ALTER TABLE CLINIC.HAS_SYMPTOM DROP CONSTRAINT FK_HAS_SYMPTOM_VST_ID;

ALTER TABLE CLINIC.CONTACT_INFO DROP CONSTRAINT FK_CONTACT_INFO_LOC_ID;

ALTER TABLE CLINIC.DOCUMENT DROP CONSTRAINT FK_DOCUMENT_VST_ID;

ALTER TABLE CLINIC.PTNT DROP CONSTRAINT FK_PTNT_PID;

ALTER TABLE CLINIC.TK_MSRMNT DROP CONSTRAINT FK_TK_MSRMNT_VST_ID;

ALTER TABLE CLINIC.VISIT DROP CONSTRAINT FK_VISIT_PID;

ALTER TABLE CLINIC.TREATED_WITH DROP CONSTRAINT FK_TREATED_WITH_TRTMNT_ID;

ALTER TABLE CLINIC.TK_MSRMNT DROP CONSTRAINT FK_TK_MSRMNT_MSRMNT_ID;

ALTER TABLE CLINIC.TREATED_WITH DROP CONSTRAINT FK_TREATED_WITH_VST_ID;

ALTER TABLE CLINIC.CONTACT_INFO DROP CONSTRAINT FK_CONTACT_INFO_PID;

ALTER TABLE CLINIC.DCTR DROP CONSTRAINT FK_DCTR_PID;

ALTER TABLE CLINIC.DOCUMENT DROP CONSTRAINT FK_DOCUMENT_RDR_ID;

ALTER TABLE CLINIC.USR DROP CONSTRAINT FK_USR_PID;

ALTER TABLE CLINIC.HAS_SYMPTOM DROP CONSTRAINT FK_HAS_SYMPTOM_SMPTM_ID;

ALTER TABLE CLINIC.DCTR_ORDER DROP CONSTRAINT FK_DCTR_ORDER_VST_ID;

ALTER TABLE CLINIC.DIAGANOSED_WITH DROP CONSTRAINT FK_DIAGANOSED_WITH_VST_ID;

ALTER TABLE CLINIC.DCTR DROP CONSTRAINT SYS_C008681;

ALTER TABLE CLINIC.LCTN DROP CONSTRAINT SYS_C008697;

ALTER TABLE CLINIC.DOCUMENT DROP CONSTRAINT SYS_C008692;

ALTER TABLE CLINIC.HAS_SYMPTOM DROP CONSTRAINT SYS_C008695;

ALTER TABLE CLINIC.PTNT DROP CONSTRAINT SYS_C008703;

ALTER TABLE CLINIC.NRS DROP CONSTRAINT SYS_C008701;

ALTER TABLE CLINIC.DIAGANOSIS DROP CONSTRAINT SYS_C008690;

ALTER TABLE CLINIC.DIAGANOSED_WITH DROP CONSTRAINT SYS_C008686;

ALTER TABLE CLINIC.VISIT DROP CONSTRAINT SYS_C008715;

ALTER TABLE CLINIC.TREATED_WITH DROP CONSTRAINT SYS_C008711;

ALTER TABLE CLINIC.TK_MSRMNT DROP CONSTRAINT SYS_C008708;

ALTER TABLE CLINIC.USR DROP CONSTRAINT SYS_C008677;

ALTER TABLE CLINIC.MEASURMENT DROP CONSTRAINT SYS_C008699;

ALTER TABLE CLINIC.PRSN DROP CONSTRAINT SYS_C008675;

ALTER TABLE CLINIC.CONTACT_INFO DROP CONSTRAINT SYS_C008673;

ALTER TABLE CLINIC.TREATMENT DROP CONSTRAINT SYS_C008713;

ALTER TABLE CLINIC.SEQUENCE DROP CONSTRAINT SYS_C008301;

ALTER TABLE CLINIC.DCTR_ORDER DROP CONSTRAINT SYS_C008683;

ALTER TABLE CLINIC.SYMPTOM DROP CONSTRAINT SYS_C008705;

DROP INDEX CLINIC.SYS_C008681;

DROP INDEX CLINIC.SYS_C008687;

DROP INDEX CLINIC.SYS_C008695;

DROP INDEX CLINIC.SYS_C008715;

DROP INDEX CLINIC.SYS_C008673;

DROP INDEX CLINIC.SYS_C008679;

DROP INDEX CLINIC.SYS_C008692;

DROP INDEX CLINIC.SYS_C008703;

DROP INDEX CLINIC.SYS_C008677;

DROP INDEX CLINIC.SYS_C008683;

DROP INDEX CLINIC.SYS_C008701;

DROP INDEX CLINIC.SYS_C008708;

DROP INDEX CLINIC.SYS_C008686;

DROP INDEX CLINIC.SYS_C008301;

DROP INDEX CLINIC.SYS_C008699;

DROP INDEX CLINIC.SYS_C008711;

DROP INDEX CLINIC.SYS_C008675;

DROP INDEX CLINIC.SYS_C008678;

DROP INDEX CLINIC.SYS_C008688;

DROP INDEX CLINIC.SYS_C008705;

DROP INDEX CLINIC.SYS_C008713;

DROP INDEX CLINIC.SYS_C008697;

DROP INDEX CLINIC.SYS_C008690;

DROP TABLE CLINIC.PRSN;

DROP TABLE CLINIC.NRS;

DROP TABLE CLINIC.DCTR;

DROP TABLE CLINIC.DIAGANOSED_WITH;

DROP TABLE CLINIC.TK_MSRMNT;

DROP TABLE CLINIC.TREATMENT;

DROP TABLE CLINIC.DIAGANOSIS;

DROP TABLE CLINIC.DCTR_ORDER;

DROP TABLE CLINIC.USR;

DROP TABLE CLINIC.SYMPTOM;

DROP TABLE CLINIC.PTNT;

DROP TABLE CLINIC.LCTN;

DROP TABLE CLINIC.HAS_SYMPTOM;

DROP TABLE CLINIC.SEQUENCE;

DROP TABLE CLINIC.VISIT;

DROP TABLE CLINIC.CONTACT_INFO;

DROP TABLE CLINIC.DOCUMENT;

DROP TABLE CLINIC.MEASURMENT;

DROP TABLE CLINIC.TREATED_WITH;

