ALTER TABLE CONTACT_INFO DROP CONSTRAINT FK_CONTACT_INFO_LOC_ID
ALTER TABLE CONTACT_INFO DROP CONSTRAINT FK_CONTACT_INFO_PID
ALTER TABLE USR DROP CONSTRAINT FK_USR_PID
ALTER TABLE DCTR DROP CONSTRAINT FK_DCTR_PID
ALTER TABLE DCTR_ORDER DROP CONSTRAINT FK_DCTR_ORDER_VST_ID
ALTER TABLE DIAGANOSED_WITH DROP CONSTRAINT FK_DIAGANOSED_WITH_DGNSS_ID
ALTER TABLE DIAGANOSED_WITH DROP CONSTRAINT FK_DIAGANOSED_WITH_VST_ID
ALTER TABLE DOCUMENT DROP CONSTRAINT FK_DOCUMENT_VST_ID
ALTER TABLE DOCUMENT DROP CONSTRAINT FK_DOCUMENT_RDR_ID
ALTER TABLE HAS_SYMPTOM DROP CONSTRAINT FK_HAS_SYMPTOM_VST_ID
ALTER TABLE HAS_SYMPTOM DROP CONSTRAINT FK_HAS_SYMPTOM_SMPTM_ID
ALTER TABLE NRS DROP CONSTRAINT FK_NRS_PID
ALTER TABLE PTNT DROP CONSTRAINT FK_PTNT_PID
ALTER TABLE TK_MSRMNT DROP CONSTRAINT FK_TK_MSRMNT_MSRMNT_ID
ALTER TABLE TK_MSRMNT DROP CONSTRAINT FK_TK_MSRMNT_VST_ID
ALTER TABLE TREATED_WITH DROP CONSTRAINT FK_TREATED_WITH_TRTMNT_ID
ALTER TABLE TREATED_WITH DROP CONSTRAINT FK_TREATED_WITH_VST_ID
ALTER TABLE VISIT DROP CONSTRAINT FK_VISIT_PID
DROP TABLE CONTACT_INFO CASCADE CONSTRAINTS
DROP TABLE PRSN CASCADE CONSTRAINTS
DROP TABLE USR CASCADE CONSTRAINTS
DROP TABLE DCTR CASCADE CONSTRAINTS
DROP TABLE DCTR_ORDER CASCADE CONSTRAINTS
DROP TABLE DIAGANOSED_WITH CASCADE CONSTRAINTS
DROP TABLE DIAGANOSIS CASCADE CONSTRAINTS
DROP TABLE DOCUMENT CASCADE CONSTRAINTS
DROP TABLE HAS_SYMPTOM CASCADE CONSTRAINTS
DROP TABLE LCTN CASCADE CONSTRAINTS
DROP TABLE MEASURMENT CASCADE CONSTRAINTS
DROP TABLE NRS CASCADE CONSTRAINTS
DROP TABLE PTNT CASCADE CONSTRAINTS
DROP TABLE SYMPTOM CASCADE CONSTRAINTS
DROP TABLE TK_MSRMNT CASCADE CONSTRAINTS
DROP TABLE TREATED_WITH CASCADE CONSTRAINTS
DROP TABLE TREATMENT CASCADE CONSTRAINTS
DROP TABLE VISIT CASCADE CONSTRAINTS
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN_TABLE'
